# Generated by Django 3.1.7 on 2021-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpersonalprofile',
            name='step',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
