# Generated by Django 3.1.7 on 2021-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientpersonalprofile_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpersonalprofile',
            name='step',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
