# Generated by Django 3.1.7 on 2021-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_staff'),
        ('patient', '0007_followunfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientpersonalprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='patientpersonalprofile',
            name='language',
            field=models.ManyToManyField(to='account.Language'),
        ),
    ]
