# Generated by Django 3.1.7 on 2021-03-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20210318_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpurchasehistory',
            name='charge_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
