# Generated by Django 3.1.7 on 2021-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_callrequest'),
        ('patient', '0012_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='language_call', to='account.Language'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='call_status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Waiting'), (3, 'Not Attended'), (4, 'Pending'), (5, 'Accepted'), (6, 'Rejected')], default=4),
        ),
    ]
