# Generated by Django 3.1.7 on 2021-03-30 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0013_auto_20210326_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdisease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_desease', to=settings.AUTH_USER_MODEL),
        ),
    ]
