# Generated by Django 3.1.7 on 2021-03-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_auto_20210330_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicalehistory',
            name='wallet',
        ),
    ]
