# Generated by Django 3.1.7 on 2021-03-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_remove_patientmedicalehistory_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='call_status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Waiting'), (3, 'Not Attended'), (4, 'Pending'), (5, 'Rejected')], default=4),
        ),
    ]
