# Generated by Django 3.1.7 on 2021-04-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_callrequestnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callrequestnotification',
            old_name='patient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='callrequestnotification',
            old_name='doctor',
            new_name='sender',
        ),
    ]
