# Generated by Django 3.1.7 on 2021-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20210405_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequestnotification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accept'), (3, 'Reject')], default=1),
        ),
    ]
