# Generated by Django 3.1.7 on 2021-04-06 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0020_callrequestnotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequestnotification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'CALL REQUEST'), (2, 'CLINIC STATUS')], default=1),
        ),
        migrations.AlterField(
            model_name='callrequestnotification',
            name='call_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_notif_request', to='patient.callrequest'),
        ),
        migrations.AlterField(
            model_name='callrequestnotification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accept'), (3, 'Reject'), (4, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='followunfollow',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
