# Generated by Django 3.1.7 on 2021-04-09 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_summary_summaryattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
