# Generated by Django 3.1.7 on 2021-04-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0024_labresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_lab_result', to='account.user'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_summary', to='account.user'),
        ),
    ]
