# Generated by Django 3.1.7 on 2021-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_auto_20210409_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
