# Generated by Django 3.1.7 on 2021-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0026_auto_20210409_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequestnotification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'CALL REQUEST'), (2, 'CLINIC STATUS'), (3, 'FOLLOW')], default=1),
        ),
    ]
