# Generated by Django 3.1.7 on 2021-04-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_auto_20210412_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='call_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='call_request_summary', to='patient.callrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='other_investigation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other Investigations'),
        ),
    ]
