# Generated by Django 3.1.7 on 2021-04-19 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0028_auto_20210414_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='labresult',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_lab_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_date',
            field=models.DateField(verbose_name='Created Date'),
        ),
        migrations.CreateModel(
            name='LabResultAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('deleted', models.BooleanField(blank=True, default=False, verbose_name='Delete')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=patient.models.lab_attachment)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_lab', to='patient.labresult')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
