# Generated by Django 3.1.7 on 2021-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0030_callrequest_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='call_status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Waiting'), (3, 'Not Attended'), (4, 'Pending'), (5, 'Rejected'), (6, 'In Progress')], default=4),
        ),
        migrations.AlterField(
            model_name='patientwallet',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='planpurchasehistory',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
    ]
