# Generated by Django 3.1.7 on 2021-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0031_auto_20210426_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
