# Generated by Django 3.1.7 on 2021-04-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_labresult_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='clinic',
        ),
    ]
