# Generated by Django 3.1.7 on 2021-04-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0033_remove_labresult_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='call_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_request', to='patient.callrequest'),
        ),
    ]
